{% set name = "drf-api-tracking" %}
{% set version = "1.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drf-api-tracking-{{ version }}.tar.gz
  sha256: 0f085479fc67c8d4d2e5a8d5059bfe853eed2ba2d4ec4063fa5438d11b3f687c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - django >=1.7
    - djangorestframework >=3
    - python >={{ python_min }}
    - pytz

test:
  imports:
    - rest_framework_tracking
    - rest_framework_tracking.migrations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lingster/drf-api-tracking
  summary: Utils to log Django Rest Framework requests to the database
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
